/**
 * Piano sample presets for PianoApp.
 * Each preset defines a set of audio samples that can be loaded by Tone.js Sampler.
 *
 * NOTE: Only 'salamander' is currently available locally.
 * Other presets are placeholders for future expansion.
 */

export const PIANO_PRESETS = {
  salamander: {
    id: 'salamander',
    name: 'Yamaha C5',
    description: 'Salamander Grand Piano — warm & natural',
    baseUrl: '/audio/salamander/',
    loaded: true,
    size: '2MB',
    license: 'CC-BY 3.0',
    source: 'https://freepats.zenvoid.org/Piano/acoustic-grand-piano.html',
    sampleMapKey: 'sharp', // A0, C1, Ds1, Fs1...
  },
  steinway: {
    id: 'steinway',
    name: 'Grand Piano',
    description: 'MusyngKite Acoustic Grand — warm concert grand',
    baseUrl: '/audio/steinway/',
    loaded: true,
    size: '1.6MB',
    license: 'Free / MusyngKite',
    source: 'https://github.com/gleitz/midi-js-soundfonts',
    sampleMapKey: 'flat', // A0, Ab1, Bb1, Db1, Eb1, Gb1...
  },
  bright_grand: {
    id: 'bright_grand',
    name: 'Bright Grand',
    description: 'MusyngKite Bright Acoustic — brilliant & projecting',
    baseUrl: '/audio/bright_grand/',
    loaded: true,
    size: '1.9MB',
    license: 'Free / MusyngKite',
    source: 'https://github.com/gleitz/midi-js-soundfonts',
    sampleMapKey: 'flat',
  },
  bosendorfer: {
    id: 'bosendorfer',
    name: 'Bösendorfer 290',
    description: 'Dark & rich imperial tone',
    baseUrl: '/audio/bosendorfer/',
    loaded: false,
    size: 'N/A',
    license: 'N/A',
    source: null,
    sampleMapKey: 'sharp',
  },
};

export const DEFAULT_PRESET = 'salamander';

/**
 * SAMPLE_MAP defines the note-to-file mapping used by Tone.js Sampler.
 * This map is shared across all presets that follow the Salamander naming convention.
 * Presets with different file naming would need their own map.
 */
export const SAMPLE_MAP = {
  A0: 'A0.mp3',
  C1: 'C1.mp3',
  'D#1': 'Ds1.mp3',
  'F#1': 'Fs1.mp3',
  A1: 'A1.mp3',
  C2: 'C2.mp3',
  'D#2': 'Ds2.mp3',
  'F#2': 'Fs2.mp3',
  A2: 'A2.mp3',
  C3: 'C3.mp3',
  'D#3': 'Ds3.mp3',
  'F#3': 'Fs3.mp3',
  A3: 'A3.mp3',
  C4: 'C4.mp3',
  'D#4': 'Ds4.mp3',
  'F#4': 'Fs4.mp3',
  A4: 'A4.mp3',
  C5: 'C5.mp3',
  'D#5': 'Ds5.mp3',
  'F#5': 'Fs5.mp3',
  A5: 'A5.mp3',
  C6: 'C6.mp3',
  'D#6': 'Ds6.mp3',
  'F#6': 'Fs6.mp3',
  A6: 'A6.mp3',
  C7: 'C7.mp3',
  'D#7': 'Ds7.mp3',
  'F#7': 'Fs7.mp3',
  A7: 'A7.mp3',
  C8: 'C8.mp3',
};

// MusyngKite / gleitz format — uses flat notation (Ab, Bb, Db, Eb, Gb)
export const SAMPLE_MAP_FLAT = {
  A0: 'A0.mp3',
  'Bb0': 'Bb0.mp3',
  B0: 'B0.mp3',
  C1: 'C1.mp3',
  'Db1': 'Db1.mp3',
  D1: 'D1.mp3',
  'Eb1': 'Eb1.mp3',
  E1: 'E1.mp3',
  F1: 'F1.mp3',
  'Gb1': 'Gb1.mp3',
  G1: 'G1.mp3',
  'Ab1': 'Ab1.mp3',
  A1: 'A1.mp3',
  'Bb1': 'Bb1.mp3',
  B1: 'B1.mp3',
  C2: 'C2.mp3',
  'Db2': 'Db2.mp3',
  D2: 'D2.mp3',
  'Eb2': 'Eb2.mp3',
  E2: 'E2.mp3',
  F2: 'F2.mp3',
  'Gb2': 'Gb2.mp3',
  G2: 'G2.mp3',
  'Ab2': 'Ab2.mp3',
  A2: 'A2.mp3',
  'Bb2': 'Bb2.mp3',
  B2: 'B2.mp3',
  C3: 'C3.mp3',
  'Db3': 'Db3.mp3',
  D3: 'D3.mp3',
  'Eb3': 'Eb3.mp3',
  E3: 'E3.mp3',
  F3: 'F3.mp3',
  'Gb3': 'Gb3.mp3',
  G3: 'G3.mp3',
  'Ab3': 'Ab3.mp3',
  A3: 'A3.mp3',
  'Bb3': 'Bb3.mp3',
  B3: 'B3.mp3',
  C4: 'C4.mp3',
  'Db4': 'Db4.mp3',
  D4: 'D4.mp3',
  'Eb4': 'Eb4.mp3',
  E4: 'E4.mp3',
  F4: 'F4.mp3',
  'Gb4': 'Gb4.mp3',
  G4: 'G4.mp3',
  'Ab4': 'Ab4.mp3',
  A4: 'A4.mp3',
  'Bb4': 'Bb4.mp3',
  B4: 'B4.mp3',
  C5: 'C5.mp3',
  'Db5': 'Db5.mp3',
  D5: 'D5.mp3',
  'Eb5': 'Eb5.mp3',
  E5: 'E5.mp3',
  F5: 'F5.mp3',
  'Gb5': 'Gb5.mp3',
  G5: 'G5.mp3',
  'Ab5': 'Ab5.mp3',
  A5: 'A5.mp3',
  'Bb5': 'Bb5.mp3',
  B5: 'B5.mp3',
  C6: 'C6.mp3',
  'Db6': 'Db6.mp3',
  D6: 'D6.mp3',
  'Eb6': 'Eb6.mp3',
  E6: 'E6.mp3',
  F6: 'F6.mp3',
  'Gb6': 'Gb6.mp3',
  G6: 'G6.mp3',
  'Ab6': 'Ab6.mp3',
  A6: 'A6.mp3',
  'Bb6': 'Bb6.mp3',
  B6: 'B6.mp3',
  C7: 'C7.mp3',
  'Db7': 'Db7.mp3',
  D7: 'D7.mp3',
  'Eb7': 'Eb7.mp3',
  E7: 'E7.mp3',
  F7: 'F7.mp3',
  'Gb7': 'Gb7.mp3',
  G7: 'G7.mp3',
  'Ab7': 'Ab7.mp3',
  A7: 'A7.mp3',
  C8: 'C8.mp3',
};
